added 2 items to ItemCooldowns
SkyblockerMod/Skyblocker pull request #1018
Opened 2024-10-07 23:18 UTC by VeritasDL

added Rouge Sword and Ink Wand

2024-10-08 06:35 UTC, kevinthegreat1 approved these changes

2024-10-11 01:51 UTC, kevinthegreat1 reviewed
You have a lot of duplicate code, can you use a method please.

2024-10-11 02:51 UTC, VeritasDL commented
pardon my tism, this might be slightly better?

2024-10-11 02:58 UTC, kevinthegreat1 requested changes

2024-10-11 02:58 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/item/ItemCooldowns.java
> +				}
```suggestion
				handleItemCooldown(GRAPPLING_HOOK_ID, 2000, player.fishHook != null && !isWearingBatArmor(player));
```

2024-10-11 02:58 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/item/ItemCooldowns.java
> +
It doesn't make sense to place these two methods here. Maybe after `onItemInteract`?

2024-10-11 02:58 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/item/ItemCooldowns.java
> +		switch (usedItemId) {
Can you sort this switch by the time while you're at it? You also have two entries for `30000`.

2024-10-11 03:35 UTC, VeritasDL commented
weeeee

2024-10-11 03:39 UTC, kevinthegreat1 approved these changes
Looks great, thanks.

2024-10-21 04:56 UTC, merged