Option to share fairy grottos
SkyblockerMod/Skyblocker pull request #1072
Opened 2024-12-10 15:49 UTC by kevinthegreat1

2024-12-10 17:17 UTC, lunaynx commented on src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
> +		public boolean shareFairyGrotto = true;
This really should be off by default.

2024-12-10 21:34 UTC, AzureAaron requested changes
People who don't want to share fairy grottos shouldn't receive them either. If you want to take you have to give as well.

2024-12-12 00:38 UTC, kevinthegreat1 commented
Updated. Not tested, however.

2024-12-12 21:39 UTC, AzureAaron approved these changes

2024-12-13 03:16 UTC, merged