Profiled data api
SkyblockerMod/Skyblocker pull request #1102
Opened 2024-12-24 07:34 UTC by kevinthegreat1

Replaces pet cache, end stats, museum, and accessory helper.

WIP cause waiting on museum hud and powder mining tracker.

2024-12-27 02:27 UTC, kevinthegreat1 commented
It's usable as is, so I'll mark this as ready.

2025-01-04 00:46 UTC, AzureAaron requested changes

2025-01-04 00:46 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/utils/profile/ProfiledData.java
> +				data = codec.parse(compressed ? JsonOps.COMPRESSED : JsonOps.INSTANCE, SkyblockerMod.GSON.fromJson(reader, JsonObject.class)).getOrThrow();
1. How is this atomic? there is no volatile or VarHandle here that would indicate that this is the case
2. Use `JsonParser` instead of `fromJson`

2025-01-04 00:46 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/utils/profile/ProfiledData.java
> +		ClientLifecycleEvents.CLIENT_STOPPING.register(client -> save());
You could stuff this at the end of the constructor and delete the method.

2025-01-04 00:46 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/utils/profile/ProfiledData.java
> +	public void save() {
Some parts of the mod saved things on-demand async and forcing sync when that isn't wanted (stalling the render thread) isn't good, there should be a parameter added to make it run async.

The best way to do this would be to wrap the operation in a runnable and run it async or not.

2025-01-04 00:46 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/utils/profile/ProfiledData.java
> +	public boolean containsKey(UUID uuid, String profileId) {
I'm not sure the `containsKey` (mainly the key) terminology is very clear or helpful here. It would be better off as `containsSave` (not great) or smth similar but you get the idea.

2025-01-04 00:48 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/profile/ProfiledData.java
> +				data = codec.parse(compressed ? JsonOps.COMPRESSED : JsonOps.INSTANCE, SkyblockerMod.GSON.fromJson(reader, JsonObject.class)).getOrThrow();
I meant the `=` is atomic, so we can always safely access `data`. Afaik object reference set is atomic.

2025-01-04 00:48 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/profile/ProfiledData.java
> +		ClientLifecycleEvents.CLIENT_STOPPING.register(client -> save());
I need to return a completable future.

2025-01-05 02:06 UTC, merged