Add seen waypoint
SkyblockerMod/Skyblocker pull request #1108
Opened 2024-12-27 01:50 UTC by kevinthegreat1

These waypoints will start rendering through walls when the player sees them.

Migrated egg finer and ender nodes to this system.

2024-12-30 21:58 UTC, AzureAaron requested changes

2024-12-30 21:58 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/utils/waypoint/SeenWaypoint.java
> +			BlockHitResult blockHitResult = client.world.raycast(new RaycastContext(client.player.getEyePos(), Vec3d.ofCenter(pos), RaycastContext.ShapeType.COLLIDER, RaycastContext.FluidHandling.NONE, client
I think that it should have to be seen for a certain number of seconds to count, too often with egg waypoints I spin my camera briefly not even noticing the egg and it shows me the waypoint.

2025-01-07 02:37 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/waypoint/SeenWaypoint.java
> +			BlockHitResult blockHitResult = client.world.raycast(new RaycastContext(client.player.getEyePos(), Vec3d.ofCenter(pos), RaycastContext.ShapeType.COLLIDER, RaycastContext.FluidHandling.NONE, client
I think that could be added at a later point. I made it like this since it's supposed to help you see things.

2025-02-12 16:43 UTC, kevinthegreat1 commented
I think I'll just merge this for now since it keeps the current behavior.

2025-02-15 02:11 UTC, merged