Garden Tweaks & Features
SkyblockerMod/Skyblocker pull request #1118
Opened 2024-12-31 08:59 UTC by WannaBeIan

- [x] Added an option to view required crops in the visitor helper as stacks + remainder.

- [x] Visitor Helper now works outside of the Garden by default but includes a new setting to lock it to the Garden.

- [x] Fixed the regex for Farming XP so it works correctly and now displays your XP/h, even at max farming level.

- [x] Added decimals for more precise XP/h and Blocks/s calculations.

- [x] Visitors requesting the same crops are grouped together, displaying a sum of the required crops.

![New Settings](https://i.imgur.com/BAs39JB.png)

![Stacks + Grouped Visitors](https://i.imgur.com/cZsyU3N.png)

![Fixed XP/hr Counter + Fancy Dots](https://i.imgur.com/l6NDg6j.png)

I am aware the code is pretty messy its been some time since I've sat down and type something up

Let me know if anything needs to be fixed, and I'll take care of it!

2025-01-02 05:17 UTC, kevinthegreat1 requested changes

2025-01-02 05:17 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java
> +	public static void onMouseClicked(double mouseX, double mouseY, int mouseButton, TextRenderer textRenderer) {
Definitely not a fan of the logic as is. I have a couple of suggestions:
1. You could use `SortedMap<String, Object2IntMap<Pair<String, String>>>` for `itemMap` instead, which won't keep one visitor's items together, but they usually only request one item anyways.
2. You could replace the mouse click logic with `ClickEvent` and `Screen#handleTextClick`. See how `ChatScreen#mouseClicked` does it. This way, you only have the rendering logic, and not the mouse clicked logic.

2025-01-02 05:17 UTC, kevinthegreat1 commented on src/main/resources/assets/skyblocker/lang/en_us.json
> +  "skyblocker.config.farming.garden.visitorHelperGardenOnly": "Visitor helper (Garden Only)",
I'd change this name to simply "Garden Only".

2025-01-02 09:36 UTC, kevinthegreat1 commented
After a discussion, we think the visitor helper options would be better in a group. If you can also do that it’d be great.

2025-01-03 20:43 UTC, WannaBeIan commented on src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java
> +			boolean isGardenLocation = Utils.getLocationRaw().equals("garden");
I've actually added a helper method into utils for this, but added that way after I made changes here. I'm getting close to pushing a final update for the VisitorHelper that also makes sure that the item map is linked based on the profileId so it isn't showing trades from other profiles.

I plan on eventually "revamping" it to make everything less of an eye sore but for now it'll work fine.

2025-01-06 03:52 UTC, WannaBeIan commented
Sorry for the messy commits. this should be everything requested change wise.
- VisitorHelper is now it's own group and work's/looks really good.
- Added a "Vacuum Solver" which just makes a guess based on the angry_witch partcles and places a waypoint at the location
- Added "Pest Highlighter" which applies a glow effect on pests.
- Made a little change in MayorUtils causing an error when no minister is found.
- Made the changes requested in the Farming hud, and when you're at max farming rather than it showing xp/0 I have farmingXpPercentProgress clamped between 0/100
- Noticed while going through the config that the description of suppliesAndFuelWaypointType was using an old translation so I updated that as well

2025-01-06 05:07 UTC, Emirlol commented on src/main/java/de/hysky/skyblocker/utils/mayor/MayorUtils.java
> +					}
This seems a little redundant, as any exception thrown would land in the catch block which results in the same thing.

This does clarify it a bit more, so it could be kept. But the catch block's warn message must also be changed as it can no longer be caused by mayorless ministers and could cause confusion when something goes wrong.

2025-01-06 05:10 UTC, Emirlol commented on src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHud.java
> +	private static final Pattern FARMING_XP = Pattern.compile("§3\\+(?<xp>\\d+(?:\\.\\d+)?) Farming \\((?<percent>[\\d,]+(?:\\.\\d+)?%|[\\d,]+/[\\d,]+)\\)");
I'd also recommend `Formatting.strip`ping the message and removing the color code from the regex.

2025-01-06 05:41 UTC, WannaBeIan commented
The VacuumSolver could be improved by checking the scoreboard location line for the pest icon before rendering the waypoint, instead of rendering it regardless of pests. This can be addressed in a future PR.

2025-02-12 22:21 UTC, kevinthegreat1 approved these changes
LGTM. I've made some clean up and fixes if you want to take a look.

2025-02-12 23:16 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/config/configs/FarmingConfig.java
> +	public static class visitorHelper {
`VisitorHelper`

2025-02-12 23:16 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/garden/VacuumSolver.java
> +	private static void reset() {
Shouldn't this reset the destination too?

2025-02-12 23:16 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/Visitor.java
> +public record Visitor(Text name, ItemStack head, Map<Text, Integer> requiredItems) {
Should use an `Object2IntMap`

2025-02-12 23:16 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java
> +		for (Map.Entry<Text, Integer> entry : groupedItems.entrySet()) {
You need to use the type specific iterator

2025-02-12 23:16 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java
> +		for (Map.Entry<Text, Integer> entry : groupedItems.entrySet()) {
Type specific iterator

2025-02-12 23:16 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/garden/VacuumSolver.java
> +		if (fixedDestination == null) {
Maybe also check if the person is in the garden and stuff?

2025-02-13 16:18 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/garden/VacuumSolver.java
> +	private static void reset() {
I tried to use this solver but couldn't figure it out so @WannaBeIan.

2025-02-13 16:50 UTC, kevinthegreat1 commented
The vacuum solver needs a bit of testing and the potential bugs Aaron pointed out. I wasn't able to figure out how to use it.

2025-02-25 02:25 UTC, WannaBeIan commented on src/main/java/de/hysky/skyblocker/skyblock/garden/VacuumSolver.java
> +	private static void reset() {
Like I mentioned the code for the Vacuum Solver is really bad I mean it "kinda" worked it would get the particles and find where they end but it wouldn't estimate where the pest was I looked at some code from skyhanni as reference and that's where I got with it.

2025-02-25 17:49 UTC, LifeIsAParadox requested changes
First of all, thanks for the new features you added! I really appreciate the effort you put into improving the project.

I just have one small nitpick regarding the Vacuum Solver, and I also encountered a crash during testing.

Other than that, great work!

2025-02-25 17:49 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java
> +				.forEach(parts -> visitor.addRequiredItem(Text.literal(parts[0].trim()), Integer.parseInt(parts[1].trim())));
`Caused by: java.lang.NumberFormatException: For input string: "1,024"`
crash lol
Full log (https://mclo.gs/BQSI0sc)

Maybe 
```diff
- Integer.parseInt(parts[1].trim())
+ Integer.parseInt(parts[1].trim().replace(",", ""))
```
 could help

2025-02-25 17:49 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/garden/VacuumSolver.java
> +	private static void reset() {
I tested the Vacuum "Helper", but to be honest, it raised more questions than it actually helped. Maybe it just didn’t work as intended for me, but I think the logic could either be improved or perhaps the helper isn’t needed (at least for now).

Also, the red cube should probably disappear after some time or when switching worlds, otherwise, it just stays there permanently, which might not be ideal.

2025-02-28 04:09 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java
> +				.forEach(parts -> visitor.addRequiredItem(Text.literal(parts[0].trim()), Integer.parseInt(parts[1].trim())));
Fixed in 57f07c1.

2025-02-28 04:11 UTC, kevinthegreat1 approved these changes
I've temporarily removed the vacuum solver, and you can open another pr with it once you fix the bugs. We'll merge this first.

2025-03-03 04:08 UTC, merged

2025-03-03 04:09 UTC, kevinthegreat1 commented
Please let me know if you need help with getting the vacuum solver back to work on it further.