ItemList Changes
SkyblockerMod/Skyblocker pull request #1119
Opened 2024-12-31 13:05 UTC by Manchick0

This update introduces a bunch of changes to the ItemList feature, to hopefully enhance user experience. Most importantly, you can now filter out specific elements in the list to narrow down the results. The lore search now works properly, and you're now able to use the wiki lookup key in the recipe book. Besides all that, shift-clicking on the recipe result button will suggest the recipe to the player using the `viewrecipe` command, to allow quick super-craft access.

_P.S. The second commit only exists because I forgot to check those files in the first one._

2025-01-02 05:38 UTC, kevinthegreat1 requested changes
Overall pretty good logic, you can decide to accept the nit picks as you see fit.

2025-01-02 05:38 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/FilterOption.java
> +	public Identifier identify() {
nit: typo?

2025-01-02 05:38 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/FilterOption.java
> +public enum FilterOption implements Identifiable {
This looks great! nit: could impl Predicate? (your choice)

2025-01-02 05:38 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
> +			synchronized (this) {
Why sync?

2025-01-02 05:38 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
> +		if (this.recipeView && Screen.hasShiftDown()) {
Did you mean to also check if `button == 1` (left click)?

2025-01-02 05:38 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeBookWidget.java
> +	// with the filtering button. (26 - 14) = 12 - 4 = 8
This confused me a bit lol.
```suggestion
	// with the filtering button. (26 - 14) - 4 = 12 - 4 = 8
```

2025-01-02 05:38 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeBookWidget.java
> +		});
```suggestion
		this.filterOption.setTextSupplier(option -> Text.translatable("skyblocker.config.general.itemList.filter." + option.name().toLowerCase(Locale.ENGLISH)));
```

2025-01-02 05:38 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/Identifiable.java
Btw no need for this, could just use supplier.

2025-01-02 05:38 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/render/gui/CyclingTextureWidget.java
> +		currentIndex = (currentIndex + 1) % entries.length;
nit: `EnumUtils.cycle` if you have it in your dev env.

2025-01-02 08:54 UTC, Manchick0 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
> +			synchronized (this) {
It used to crash if the user
refiltered items while the repo was still loading

2025-01-02 09:17 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
> +			synchronized (this) {
I don’t see any other sync blocks? I don’t think that’s how you use sync?

2025-01-02 10:12 UTC, Manchick0 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
> +			synchronized (this) {
I guess it's better to just return if the repo hasn't loaded yet?

```java
public void updateSearchResults(String query, FilterOption filterOption, boolean refresh) {
    if (!ItemRepository.filesImported()) return;
    // ...
}
```

2025-01-02 22:23 UTC, kevinthegreat1 reviewed
Just one more question.

2025-01-02 22:23 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
> +		if (this.recipeView && button == 1) {
This is left click, right? The descriptions says right click tho.

2025-01-02 22:23 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
> +				return true;
Nice catch I overlooked this.

2025-01-03 09:01 UTC, Manchick0 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
> +		if (this.recipeView && button == 1) {
0 is left click?

2025-01-03 09:02 UTC, Manchick0 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
> +		if (this.recipeView && button == 1) {
I'm sure this is RMC cuz I tested everything before committing

2025-01-03 09:03 UTC, Manchick0 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
> +		if (this.recipeView && button == 1) {
and if you look into the ClickableWidget class, you can see how it specifically checks for the button type, which should be LMC, so it checks whether it's 0.

2025-01-03 09:22 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
> +		if (this.recipeView && button == 1) {
Sorry, that's my bad.

2025-01-03 09:24 UTC, kevinthegreat1 submitted a review, later dismissed
LGTM, thanks.

2025-01-03 21:39 UTC, AzureAaron requested changes

2025-01-03 21:39 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/FilterOption.java
> +			Identifier.of("skyblocker", "textures/gui/filter/items.png"));
the `skyblocker` string should use the `SkyblockerMod.NAMESPACE` constant

2025-01-03 21:39 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/FilterOption.java
> +	public boolean test(String query) {
This needs `@Override`

2025-01-03 21:39 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/FilterOption.java
> +	final Identifier texture;
these should be private if they aren't for public use

2025-01-03 21:39 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeBookWidget.java
I don't think the asserts are necessary

2025-01-03 21:44 UTC, Manchick0 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeBookWidget.java
They just fix all the warning in the IDE

2025-01-04 22:54 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeBookWidget.java
I think it makes sense to use asserts as "I know this won't be null, now stop giving me warnings."

2025-01-04 22:54 UTC, kevinthegreat1 approved these changes

2025-01-05 02:06 UTC, merged

2025-01-05 09:18 UTC, Manchick0 commented on src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeBookWidget.java
> I think it makes sense to use asserts as "I know this won't be null, now stop giving me warnings."

Or even with other boolean conditions, such as when the `children` method returns a list of three, you know for sure its size is going to be 3, so you can `assert children().size() == 3` - It's just cleaner than @SurpressWarnings