Add option to hide empty tooltips in inventories.
SkyblockerMod/Skyblocker pull request #135
Opened 2023-04-15 17:12 UTC by msg-programs

Hypixel's inventory menus sometimes use items with empty names for empty slots. When the game draws the tooltip for such an item, it just draws a small dark rectangle. This adds an option to disable these empty tooltips.

2023-04-15 21:24 UTC, Julienraptor01 requested changes
pretty good 👍, work as expected except the fact it doesn't check for skyblock

2023-04-15 21:24 UTC, Julienraptor01 commented on src/main/java/me/xmrvizzy/skyblocker/mixin/ScreenMixin.java
> +        if (SkyblockerConfig.get().general.hideEmptyTooltips && strName.equals(" ")) {
add a skyblock check by changing line to
```java
if (Utils.isOnSkyblock && SkyblockerConfig.get().general.hideEmptyTooltips && strName.equals(" ")) {
```

2023-04-16 18:07 UTC, AzureAaron approved these changes

2023-04-16 18:13 UTC, Julienraptor01 approved these changes
👌

2023-05-01 21:42 UTC, LifeIsAParadox commented
Resolve the conflict then I can make a merge

2023-05-02 17:25 UTC, msg-programs commented
Fixed it, should be ready to go now.

2023-05-02 19:25 UTC, merged