Shortcuts
SkyblockerMod/Skyblocker pull request #195
Opened 2023-07-03 01:47 UTC by kevinthegreat1

Add command shortcuts  
See config screen and `/skyblocker shortcuts`  

Fix `StackOverflowError` crash with `FrustumInvoker`

2023-07-03 02:30 UTC, AzureAaron requested changes
Aside from the requested changes, this is quite a useful feature, works great so far and makes some commands less tedious such as p transferring.

2023-07-03 02:30 UTC, AzureAaron commented on src/main/java/me/xmrvizzy/skyblocker/skyblock/shortcut/Shortcuts.java
I think there is way too many shortcuts by default, there should only be the very basic ones eg `/crimson` and probably nothing for specific areas.

This way it's far easier to setup since deleting a lot of the shortcuts (since most aren't relevant to my stage of the game) takes some time, and to make the first time seeing the screen a little less scary lol

2023-07-03 02:30 UTC, AzureAaron commented on src/main/java/me/xmrvizzy/skyblocker/skyblock/shortcut/ShortcutsConfigScreen.java
The `close` method should be overridden to add functionality which presents a warning when closing the menu before you've saved your changes.

2023-07-09 21:44 UTC, LifeIsAParadox commented
Resolve the conflicts, then I can approve the pr

2023-07-10 01:15 UTC, kevinthegreat1 commented
This pr is affected by [this bug](https://github.com/FabricMC/fabric/issues/3170). We're waiting for it to be addressed.

2023-07-20 02:10 UTC, AzureAaron submitted a review, later dismissed

2023-07-20 02:10 UTC, AzureAaron commented on src/main/java/me/xmrvizzy/skyblocker/skyblock/shortcut/Shortcuts.java
> +                dispatcher.register(literal(key.substring(1)));
If you want you could add a string parameter here so that when typing the command it doesn't show up as an error.

2023-07-20 18:12 UTC, AzureAaron approved these changes

2023-07-21 03:14 UTC, AzureAaron approved these changes

2023-07-21 03:20 UTC, merged