Title container
SkyblockerMod/Skyblocker pull request #196
Opened 2023-07-05 00:32 UTC by Futuremappermydud

Adds two things
- Title Containe r(Stackable titles, currently unmovable)
- Mania Indicator for vampire slayer, text is green if standing on green terracotta and red if standing on any other block

2023-07-05 20:04 UTC, AzureAaron requested changes

2023-07-05 20:04 UTC, AzureAaron commented on src/main/java/me/xmrvizzy/skyblocker/utils/title/TitleContainer.java
> +        context.getMatrices().pop();
These matrix transformations are unnecessary and should be removed since nothing is being rendered or affected by them.

2023-07-05 20:04 UTC, AzureAaron commented on src/main/java/me/xmrvizzy/skyblocker/utils/title/TitleContainer.java
> +    public static void init() {
There should be a space to separate the field and the method.

2023-07-05 20:04 UTC, AzureAaron commented on src/main/java/me/xmrvizzy/skyblocker/utils/title/TitleContainer.java
> +    {
This bracket should be on the line above

2023-07-07 15:30 UTC, kevinthegreat1 commented
I’m a bit confused with the implementation. The titles seem to only turn off once the player leaves slayer? Also I feel like the new system is difficult to use. I imagine a more of a drop in replacement for the title would work better and be more maintainable.

2023-07-07 15:37 UTC, Futuremappermydud commented
Title turn off when the titles active field is set to false. I’m not sure what you mean by it not being a drop in replacement how would you change it?

2023-07-07 15:45 UTC, kevinthegreat1 commented
I meant a system more similar to the current system, where I just have to call displayTitle with the parameters and a set time. I will take a closer look at this later.

2023-07-07 17:18 UTC, Futuremappermydud commented
I can implement a method that can emulate that with the scheduler if you like. The reason it isn’t built in is so I can keep them for a unknown amount of time and update their text and color dynamically like I do with the mania indicator.

2023-07-08 10:19 UTC, kevinthegreat1 commented
I refactored the code, but I noticed some things.

* Title positions are updated every frame, but tickDelta interpolates between positions. The interpolations slow down toward the end. I don't think there's a good solution for this though.
* The title container position is a bit weird when dragging in the config screen, maybe have the mouse in the middle of the container when dragging.
* The rendering code is uh... difficult to understand. Would be great if you can add some explanations or docs.

2023-07-09 02:55 UTC, kevinthegreat1 approved these changes

2023-07-09 19:00 UTC, AzureAaron approved these changes

2023-07-09 19:36 UTC, merged