Dungeon Secrets
SkyblockerMod/Skyblocker pull request #246
Opened 2023-08-16 07:47 UTC by kevinthegreat1

Adds dungeon secrets waypoints.  
This is currently usable but needs more testing, which is why I'm opening a pr now.  

## Known issues
For this to work consistently, the player needs to stay in the entrance room for about a second before going into the dungeon after the dungeon beings and the map appears.  

## Improvements
The ability to mark secrets as found or missing.  
More customizability could be added.

2023-08-17 03:33 UTC, kevinthegreat1 commented
Meant to open as draft.

2023-08-18 09:31 UTC, AzureAaron requested changes

2023-08-18 09:31 UTC, AzureAaron commented on src/main/java/me/xmrvizzy/skyblocker/skyblock/dungeon/secrets/DungeonMapUtils.java
> +    public static Pair<Vector2ic, Integer> getMapEntrancePosAndRoomSize(@NotNull MapState map) {
Should use ObjectIntPair

2023-08-18 09:31 UTC, AzureAaron commented on src/main/java/me/xmrvizzy/skyblocker/skyblock/dungeon/secrets/DungeonMapUtils.java
> +    private static Pair<Vector2ic, Integer> getMapEntrancePosAndRoomSizeAt(MapState map, Vector2ic mapPosImmutable) {
Should use ObjectIntPair

2023-08-18 09:31 UTC, AzureAaron commented on src/main/java/me/xmrvizzy/skyblocker/skyblock/dungeon/secrets/DungeonSecrets.java
> +            Pair<Vector2ic, Integer> mapEntrancePosAndSize = DungeonMapUtils.getMapEntrancePosAndRoomSize(map);
Should be ObjectIntPair

2023-08-31 04:37 UTC, AzureAaron approved these changes

2023-08-31 08:37 UTC, LifeIsAParadox approved these changes
lgtm

2023-09-01 00:03 UTC, merged