Tic Tac Toe Solver!
SkyblockerMod/Skyblocker pull request #253
Opened 2023-08-23 10:35 UTC by AzureAaron

Adds a tic tac toe solver, the solving code is mostly based off the code from the solver in Danker's Skyblock Mod.

2023-08-24 07:30 UTC, kevinthegreat1 requested changes

2023-08-27 03:42 UTC, AzureAaron commented on src/main/java/me/xmrvizzy/skyblocker/skyblock/dungeon/TicTacToe.java
> +			t.printStackTrace();
you had an extra dot here lol

2023-08-28 09:47 UTC, LifeIsAParadox approved these changes

2023-08-30 02:26 UTC, kevinthegreat1 approved these changes

2023-08-30 04:32 UTC, merged