Feat: Exotic Armor Identifier
SkyblockerMod/Skyblocker pull request #300
Opened 2023-09-13 05:34 UTC by StyStatic

- Added a setting that shows whether an item is exotic or dyed using another method

2023-09-13 22:27 UTC, LifeIsAParadox requested changes
Thank you for your pull request. I like the idea, but I have a few suggestions for improvement.

I've added hysky.de/api/color, which reflects the colors ({"ARACHNE_BOOTS":"139,0,0", ...}).

Next time, please create a branch, as it's not advisable to make changes directly to your master branch.

I also suggest merging the newest changes from our master, as there have been made updates in the priceinfotooltip with #297.

I'm also not sure if it's a good idea to display so much information in the tooltip when the expected and given colors are the same, as there's already a lot of information on an item in Hypixel SkyBlock.

In theory, it would be sufficient to have something like 'Exotic color (Spooky)' at the very bottom of the bar when the color doesn't match the expected one.

2023-09-14 04:12 UTC, StyStatic commented
Thank you for the feedback, I'll get to work.

Regarding the part about the branch, I'm not sure that's something I can fix for this PR but I'll keep it in mind for future PR's

2023-09-14 04:59 UTC, StyStatic commented
Going to keep a running list of progress made here:

- [ ] Use Http Class for API Request
- [ ] Request from HySky rather than Hypixel
- [ ] Merge incoming changes
- [ ] Color should only show in tooltip when Advanced Tooltips are shown
- [ ] Account for intended dyed armor I.E (Holly Dye)
- [ ] Remove Expected Color from tooltip
- [ ] Only show exotic type if Advanced Tooltips are disabled

2023-09-15 05:11 UTC, StyStatic commented
I made a few mistakes with git causing commits to register multiple times, but all the requested changes have been made + some changes that made the code more readable and more efficient.

2023-09-15 05:54 UTC, AzureAaron requested changes

2023-09-15 05:54 UTC, AzureAaron commented on src/main/java/me/xmrvizzy/skyblocker/SkyblockerMod.java
> +        try {
The try catch block should be moved into the actual file itself, and also shouldn't throw a runtime exception which'd cause a game crash but rather log an error and ideally disable the feature

2023-09-15 06:30 UTC, LifeIsAParadox requested changes
I don't mean this negatively, but as advice, I won't accept your pull request for now. Please create a new pull request, as the timeline would otherwise appear messed up.

2023-09-15 06:30 UTC, LifeIsAParadox commented on src/main/java/me/xmrvizzy/skyblocker/skyblock/item/exotic/DownloadColors.java
> +}
This is not necessary, you can add hysky.de/api/color here: https://github.com/SkyblockerMod/Skyblocker/blob/d30994ef9a3208980f307d69db5e5cf0d42d10ef/src/main/java/me/xmrvizzy/skyblocker/skyblock/item/PriceInfoTooltip.java#L440

and also consider using https://github.com/AzureAaron/Skyblocker/blob/d30994ef9a3208980f307d69db5e5cf0d42d10ef/src/main/java/me/xmrvizzy/skyblocker/skyblock/item/PriceInfoTooltip.java#L411.

2023-09-15 06:34 UTC, LifeIsAParadox commented
As I mentioned in the comment, I will close the pull request to not mess up the timeline, but you can create a new one with the mentioned changes.

2023-09-15 06:34 UTC, closed without merging