Item Protection
SkyblockerMod/Skyblocker pull request #335
Opened 2023-10-02 07:12 UTC by AzureAaron

Ever felt like slot locking wasn't enough to protect your items? Ever accidentally almost tossed out that prized sword of yours? Or have you ever accidentally sold a precious item to the NPC (and maybe not gotten it back)?

Now meet `/skyblocker protectItem`!

When an item is protected it's safe from:
- Being dropped while holding it, regardless of the slot being locked
- Being dropped from picking it up in your inventory then clicking outside the screen
- Being dropped via hovering over it and pressing the drop key
- Being sold to the NPC
- Being inserted into the salvaging menu

Now you'll never have to worry about your valued items!

2023-10-02 07:56 UTC, Julienraptor01 commented
Can you trigger the action via a keybind ?
It would lock the item when hovering it or holding it in hand

2023-10-03 15:56 UTC, kevinthegreat1 requested changes

2023-10-03 15:56 UTC, kevinthegreat1 commented on src/main/java/me/xmrvizzy/skyblocker/mixin/HandledScreenMixin.java
> +     * For example, using the drop key bind while hovering over an item will invoke this method to drop the players item
```suggestion
     * The naming of this method in yarn is half true, its mostly to handle slot/item interactions (which are mouse or keyboard clicks).
     * For example, using the drop key bind while hovering over an item will invoke this method to drop the players item.
```

2023-10-03 15:56 UTC, kevinthegreat1 commented on src/main/java/me/xmrvizzy/skyblocker/mixin/HandledScreenMixin.java
> +                if (this.handler instanceof GenericContainerScreenHandler handler && handler.getRows() == 6) {
```suggestion
                if (this.client != null && this.handler instanceof GenericContainerScreenHandler genericContainerScreenHandler && genericContainerScreenHandler.getRows() == 6) {
```

2023-10-04 02:14 UTC, AzureAaron commented
> Can you trigger the action via a keybind ?
> It would lock the item when hovering it or holding it in hand

This isn't really slot or item locking, intended to be applied for the long-term rather than short term

2023-10-04 03:37 UTC, kevinthegreat1 approved these changes

2023-10-04 04:28 UTC, kevinthegreat1 commented
Wait, maybe `ItemProtection` could go in the `item` package?

2023-10-04 12:34 UTC, kevinthegreat1 approved these changes

2023-10-04 16:40 UTC, merged