Fix Golden Goblin Slayer showing up as Goblin Slayer on commission HUD
SkyblockerMod/Skyblocker pull request #347
Opened 2023-10-09 16:06 UTC by 0xallie

2023-10-09 17:26 UTC, Julienraptor01 requested changes

2023-10-09 17:26 UTC, Julienraptor01 commented on src/main/java/me/xmrvizzy/skyblocker/skyblock/dwarven/DwarvenHud.java
> +                    "(?:Ice Walker|(?<!Golden )Goblin|Goblin Raid|Automaton|Sludge|Team Treasurite Member|Yog|Boss Corleone|Thyst) Slayer",
```suggestion
                    "(?:Ice Walker|Golden Goblin|(?<!Golden )Goblin|Goblin Raid|Automaton|Sludge|Team Treasurite Member|Yog|Boss Corleone|Thyst) Slayer",
```
We don't need to add a separate line

2023-10-09 18:34 UTC, kevinthegreat1 submitted a review, later dismissed

2023-10-12 12:46 UTC, kevinthegreat1 approved these changes

2023-10-13 00:31 UTC, merged