remove screens when switching island
SkyblockerMod/Skyblocker pull request #458
Opened 2023-12-23 23:57 UTC by LifeIsAParadox

Here is a small present for the community. This was on my backlog.

___

This feature removes the annoying "Loading Terrain ..." and "Reconfigure" Screens when switching island.
This feature makes the island switching experience smoother.

Comparison video

**Before:**

https://github.com/SkyblockerMod/Skyblocker/assets/19829407/f8367537-2345-487c-96a2-2a47e8649228

**After:**

https://github.com/SkyblockerMod/Skyblocker/assets/19829407/d27ac90c-d818-458d-b922-dcc89fbc5387

2023-12-24 02:56 UTC, kevinthegreat1 requested changes

2023-12-24 02:56 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/mixin/MinecraftClientMixin.java
> +    }
This removes the `reset` call when outside of skyblock. Maybe use a `ModifyArg` on the screen?
<img width="810" alt="Screenshot 2023-12-24 at 10 44 54" src="https://github.com/SkyblockerMod/Skyblocker/assets/92656833/35482061-e9c5-4136-9426-2444db3f7ab3">

2023-12-24 02:56 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/mixin/MinecraftClientMixin.java
> +    }
Using a `ModifyVariable` at head would be simpler.

2023-12-24 11:40 UTC, x-yingcan-x commented
whats the difference with `kennytvs-epic-force-close-loading-screen-mod-for-fabric`?
or which is better? (especially for skyblock)

2023-12-24 21:33 UTC, AzureAaron approved these changes

2023-12-25 04:25 UTC, kevinthegreat1 approved these changes

2023-12-25 05:41 UTC, merged

2025-08-23 15:23 UTC, luhgarlicbread commented
I think now this change has resulted in a black screen when switching servers. I don't like it, makes me feel like game is crashing or my monitor has gone off 😭   Is there a way this could be added as a toggle in the settings instead of being forced on?

2025-08-23 17:44 UTC, AzureAaron commented
> I think now this change has resulted in a black screen when switching servers. I don't like it, makes me feel like game is crashing or my monitor has gone off 😭 Is there a way this could be added as a toggle in the settings instead of being forced on?

This would be because of another mod.

2025-08-29 18:27 UTC, luhgarlicbread commented
> > I think now this change has resulted in a black screen when switching servers. I don't like it, makes me feel like game is crashing or my monitor has gone off 😭 Is there a way this could be added as a toggle in the settings instead of being forced on?
> 
> This would be because of another mod.

No- it's because of Skyblocker. When the mod is disabled, this doesn't happen.