Add dungeon score calculation on client-side
SkyblockerMod/Skyblocker pull request #500
Opened 2024-01-17 12:27 UTC by Emirlol

The score shown in the scoreboard is updated very late and is never equal to what score you would get if you went and completed the dungeon at that moment. That goes against its purpose and makes it harder to judge when the score is enough for S or S+. This PR is for calculating score client-side with the info gathered from various places, allowing the player to see when the score is enough.

I'm mostly confident in the calculation's accuracy, but I'm not very sure if I've handled mimics right so do let me know if you see any mistakes or any alternative ways to do it.

I've also added score to the HUD with customizable location & size, but it's a bit messy as I simply patched the dungeon map config with the relevant things. It could be improved further, especially if there are plans to add more HUD elements.

(sorry for creating re-creating the same pull request as I'm a bit of a newb in the matters of git. I had to change the branch)

2024-01-18 04:18 UTC, AzureAaron requested changes

2024-01-18 04:18 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
> +		return SpiritPetCache.computeIfAbsent(name, k -> {
Needs to be in a `CompletableFuture` to avoid blocking the Render Thread.

2024-01-18 04:18 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
> +	public static boolean isDungeonStarted() {
This method might make more sense to be in the DungeonManager class but not that big of a deal

2024-01-18 05:30 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
> +		return SpiritPetCache.computeIfAbsent(name, k -> {
If its already set to run off thread then no.

2024-01-19 02:50 UTC, kevinthegreat1 requested changes
Small things, otherwise looks good :)

2024-01-19 02:50 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
> +		public MimicMessages mimicMessages = new MimicMessages();
For future reference use singular for consistency.

2024-01-19 02:50 UTC, kevinthegreat1 commented on src/main/resources/assets/skyblocker/lang/en_us.json
> +  "text.autoconfig.skyblocker.option.locations.dungeons.scoreScaling": "Score Scaling",
Translation key should match the path to the config, i.e. "text.autoconfig.skyblocker.option.locations.dungeons.dungeonScore.enableScoreHud"

2024-01-19 02:50 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/mixin/ClientPlayNetworkHandlerMixin.java
> +    @WrapOperation(method = "onEntityStatus", at = @At(value = "INVOKE", target = "Lnet/minecraft/network/packet/s2c/play/EntityStatusS2CPacket;getEntity(Lnet/minecraft/world/World;)Lnet/minecraft/en
Nit: `ModifyExpressionValue` seems to do the job.

2024-01-19 02:50 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
> +									config.locations.dungeons.dungeonScore.scoreY = config.locations.dungeons.dungeonScore.scoreY + (int) ((config.locations.dungeons.dungeonScore.scoreScaling - newValue) * MinecraftClient.getI
Why does changing the scale also change the position? Not needed imo.

2024-01-19 02:50 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
> +			return armor.stream().allMatch(ItemStack::isEmpty);
I like how you're checking for mimics lol

2024-01-19 02:50 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScoreHUD.java
> +		context.drawTextWithShadow(MinecraftClient.getInstance().textRenderer, Text.literal("Score: ").append(formatScore(DungeonScore.getScore())), (int) (x / scale), (int) (y / scale), 0xFFFFFFFF);
"Score" could be made translatable.

2024-01-19 02:50 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
> +			return false;
Please use `LOGGER`

2024-01-19 02:50 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/Utils.java
> +                e.printStackTrace();
Please use `LOGGER`. Also might as well catch all exceptions, or else the completable future fails silently.

2024-01-20 04:32 UTC, AzureAaron submitted a review, later dismissed

2024-01-20 14:56 UTC, kevinthegreat1 requested changes

2024-01-20 14:56 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
> +		public MimicMessages mimicMessages = new MimicMessages();
That name is fine, no problem with the duplicate. Do you mind changing it to that?

2024-01-20 14:56 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
> +		public boolean sendMimicMessages = true;
This should also be singular.

2024-01-20 14:56 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
> +						.build())
I think these should go in the dungeon score category. If you disagree you can put it in both.

2024-01-20 14:56 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/filters/MimicFilter.java
> +    }
`onMatch` isn't called when this filter is disabled. I would suggest registering `DungeonScore#setMimicKilled` to `ClientReceiveMessageEvents.ALLOW_GAME`.

2024-01-20 15:44 UTC, kevinthegreat1 commented
Other than that, the score works great by the way!

2024-01-20 16:30 UTC, kevinthegreat1 submitted a review, later dismissed

2024-01-20 16:32 UTC, AzureAaron approved these changes

2024-01-21 17:28 UTC, kevinthegreat1 approved these changes

2024-01-21 17:35 UTC, AzureAaron approved these changes

2024-01-21 18:05 UTC, merged