Add Silverfish and Ice Fill Solvers
SkyblockerMod/Skyblocker pull request #533
Opened 2024-02-03 21:51 UTC by kevinthegreat1

Add an accident-proof silverfish solver and a static ice fill solver.  

The ice fill solver is heavily optimized but it's still a bit computation-intensive. It takes around 200\~300 ms and 100\~150 MB of memory.  

Tested in game and tests attached.

2024-02-14 23:22 UTC, LifeIsAParadox requested changes
I only looked the code for IceFill
Maybe I will look into Silverfish tomorrow

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
The code works, but some parts of it could be reduced to avoid duplication

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
> +    private static final BlockPos BOARD_3_ORIGIN = new BlockPos(18, 72, 25);
can be reduced to this:
```suggestion
    private static final BlockPos[] BOARD_ORIGINS = {
            new BlockPos(16, 70, 9),
            new BlockPos(17, 71, 16),
            new BlockPos(18, 72, 25)
    };
```

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
> +    private final List<Vector2ic> iceFillPath3 = new ArrayList<>();
```suggestion
    private final List<boolean[][]> iceFillBoards = new ArrayList<>();
    private final List<List<Vector2ic>> iceFillPaths = new ArrayList<>();
```

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
> +        super("ice-fill", "ice-path");
```suggestion
        super("ice-fill", "ice-path");
        for (int i = 0; i < 3; i++) {
            iceFillBoards.add(new boolean[i * 2 + 3][i * 2 + 3]);
            iceFillPaths.add(new ArrayList<>());
        }
```

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
> +                        context.getSource().sendFeedback(Constants.PREFIX.get().append(boardToString(INSTANCE.iceFillBoard1)));
```suggestion
                        context.getSource().sendFeedback(Constants.PREFIX.get().append(boardToString(INSTANCE.iceFillBoards.get(0))));
```

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
> +                        context.getSource().sendFeedback(Constants.PREFIX.get().append(boardToString(INSTANCE.iceFillBoard2)));
```suggestion
                        context.getSource().sendFeedback(Constants.PREFIX.get().append(boardToString(INSTANCE.iceFillBoards.get(1))));
```

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
> +                        context.getSource().sendFeedback(Constants.PREFIX.get().append(boardToString(INSTANCE.iceFillBoard3)));
```suggestion
                        context.getSource().sendFeedback(Constants.PREFIX.get().append(boardToString(INSTANCE.iceFillBoards.get(2))));
```

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
> +                        context.getSource().sendFeedback(Constants.PREFIX.get().append(INSTANCE.iceFillPath1.toString()));
```suggestion
                        context.getSource().sendFeedback(Constants.PREFIX.get().append(INSTANCE.iceFillPaths.get(0).toString()));
```

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
> +                        context.getSource().sendFeedback(Constants.PREFIX.get().append(INSTANCE.iceFillPath2.toString()));
```suggestion
                        context.getSource().sendFeedback(Constants.PREFIX.get().append(INSTANCE.iceFillPaths.get(1).toString()));
```

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
> +                        context.getSource().sendFeedback(Constants.PREFIX.get().append(INSTANCE.iceFillPath3.toString()));
```suggestion
                        context.getSource().sendFeedback(Constants.PREFIX.get().append(INSTANCE.iceFillPaths.get(2).toString()));
```

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
> +            }
```suggestion
            for (int i = 0; i < iceFillBoards.size(); i++) {
                BlockPos.Mutable pos = new BlockPos.Mutable().set(BOARD_ORIGINS[i]);
                boolean[][] iceFillBoard = iceFillBoards.get(i);
                boolean boardChanged = updateBoard(client.world, room, iceFillBoard, pos);

                if (boardChanged) {
                    solve(iceFillBoard, iceFillPaths.get(i));
                }
            }
```

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
> +            visited.remove(newPos);
```suggestion
        Vector2ic[] newPosArray = {pos.add(1, 0, new Vector2i()), pos.add(-1, 0, new Vector2i()), pos.add(0, 1, new Vector2i()), pos.add(0, -1, new Vector2i())};

        for (Vector2ic newPos : newPosArray) {
            if (newPos.x() >= 0 && newPos.x() < iceFillBoard.length && newPos.y() >= 0 && newPos.y() < iceFillBoard[0].length && !iceFillBoard[newPos.x()][newPos.y()] && !visited.contains(newPos)) {
                path.add(newPos);
                visited.add(newPos);
                List<Vector2ic> newPath = solveDfs(iceFillBoard, count - 1, path, visited);
                if (newPath != null) {
                    return newPath;
                }
                path.remove(path.size() - 1);
                visited.remove(newPos);
            }
```

2024-02-14 23:22 UTC, LifeIsAParadox commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
> +        renderPath(context, room, iceFillPath3, BOARD_3_ORIGIN);
```suggestion
        for (int i = 0; i < iceFillPaths.size(); i++) {
            renderPath(context, room, iceFillPaths.get(i), BOARD_ORIGINS[i]);
        }
```

2024-02-15 09:32 UTC, LifeIsAParadox commented
The rest of the code looks good

2024-02-15 17:49 UTC, LifeIsAParadox approved these changes

2024-02-16 04:55 UTC, AzureAaron submitted a review, later dismissed
If other people experience issues with the solver I'm sure it could be fixed, otherwise maybe it was some edge case/concurrency issue.

2024-02-17 05:27 UTC, AzureAaron commented
These merge conflicts need to be fixed.

2024-02-19 18:54 UTC, AzureAaron approved these changes

2024-02-19 19:01 UTC, merged