Disable title and chat messages for Melon/Pumpkin Dicer
SkyblockerMod/Skyblocker pull request #534
Opened 2024-02-04 23:00 UTC by Ghost-3

Removes the annoying flashing title when using Dicer.
Also filters messages about drops in chat. (Disabled by default)

2024-02-08 00:53 UTC, kevinthegreat1 requested changes
Code looks good, just some small things. Didn't test yet.

2024-02-08 00:53 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
> +	}
Can you put this right below the spider's den class, please? This makes everything easier to track and gives fewer merge conflicts.

2024-02-08 00:53 UTC, kevinthegreat1 commented on src/main/resources/assets/skyblocker/lang/en_us.json
> +  "text.autoconfig.skyblocker.option.locations.garden.dicerTitlePrevent": "Enable dicer title prevent",
Can you capitalize all the words in the string and while you're at it also the found relics string?

2024-02-08 07:29 UTC, Ghost-3 commented
All fixed.

2024-02-11 17:35 UTC, kevinthegreat1 reviewed
Can you confirm that it's still working after the latest changes? I'm not sure how to test it. Then I'll approve it.

2024-02-11 19:22 UTC, kevinthegreat1 approved these changes

2024-02-14 19:55 UTC, merged