Show the diff in the Powders widget
SkyblockerMod/Skyblocker pull request #544
Opened 2024-02-16 15:38 UTC by Ghost-3

The Powder widget shows the difference when the value of Mithril or Gemstone Powder is changed. Demo:

![2024-02-16_02 59 48](https://github.com/SkyblockerMod/Skyblocker/assets/66458557/ac16d633-5908-4197-ac06-4598732241b9)

2024-02-17 10:30 UTC, AzureAaron requested changes

2024-02-17 10:30 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/hud/HudPowderWidget.java
> +    private static void updatePowders(){
Add a space between the `()` and the `{`

2024-02-17 10:30 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/hud/HudPowderWidget.java
> +    private static final NumberFormat NUMBER_FORMAT = NumberFormat.getInstance();
Remove the American note as the `NumberFormat` instance is based off the user's locale.

2024-02-17 10:30 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/hud/HudPowderWidget.java
> +    private static int gemstonePowderDif = 0;
I would call it a "Diff" instead of "Dif" as the former is far more commonly used.

2024-02-17 10:55 UTC, Ghost-3 commented
All fixed

2024-02-18 02:55 UTC, AzureAaron requested changes
The hud powder thing doesn't seem to be parsing my amount of powder, maybe it's due to the commas? The screenshot is what the fancy tab shows (and the actual powder number is the same in the vanilla tab)
<img width="309" alt="image" src="https://github.com/SkyblockerMod/Skyblocker/assets/51387595/8c02e364-1902-4f07-96d0-e27d6d108eb1">

2024-02-18 03:18 UTC, Ghost-3 commented
> The hud powder thing doesn't seem to be parsing my amount of powder, maybe it's due to the commas? The screenshot is what the fancy tab shows (and the actual powder number is the same in the vanilla tab)
> <img width="309" alt="image" src="https://github.com/SkyblockerMod/Skyblocker/assets/51387595/8c02e364-1902-4f07-96d0-e27d6d108eb1">
> 

Yeah, it's the commas. That's why I was doing Number Format American, but someone told me it wasn't necessary and I didn't check.

It's fixed now.

2024-02-18 08:06 UTC, AzureAaron approved these changes

2024-02-18 08:23 UTC, merged