Spider's Den Server Widget
SkyblockerMod/Skyblocker pull request #553
Opened 2024-02-18 20:30 UTC by Ghost-3

Demo:

![2024-02-18_23 21 59](https://github.com/SkyblockerMod/Skyblocker/assets/66458557/f401562f-2f98-44ab-8f70-f68583f1395e)

2024-02-18 22:27 UTC, AzureAaron requested changes

2024-02-18 22:27 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/SpidersDenServerWidget.java
> +                Ico.SPIDER_EYE, "Broodmother: ", broodmotherState.formatting(), broodmotherState.text());
Have this all on the same line

2024-02-18 22:27 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/SpidersDenServerWidget.java
> +    private enum BroodmotherState {
This is missing the "Imminent" state
<img width="320" alt="image" src="https://github.com/SkyblockerMod/Skyblocker/assets/51387595/29d94170-c1fd-4276-8545-64422f0be291">

2024-02-18 22:31 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/SpidersDenServerWidget.java
> +    private enum BroodmotherState {
It's also missing the "Slain" state
<img width="269" alt="image" src="https://github.com/SkyblockerMod/Skyblocker/assets/51387595/d4a93e5d-ebe0-4053-9599-03fef5e16824">

2024-02-19 04:21 UTC, Ghost-3 commented
All fixed

2024-02-19 06:41 UTC, AzureAaron approved these changes

2024-02-19 18:38 UTC, merged