Location Change Event
SkyblockerMod/Skyblocker pull request #569
Opened 2024-02-21 22:39 UTC by Ghost-3

Event is invoked when parsing `/locraw` if the new location is different from the old one.

2024-02-25 07:21 UTC, AzureAaron requested changes

2024-02-25 07:21 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/events/LocationEvents.java
> +        void onLocationChange(Location location);
Rename the `location` parameter to better describe what information it provides as it's a big ambiguous as to whether its the new location or the old one.

2024-02-25 12:01 UTC, Ghost-3 commented
Fixed

2024-02-25 18:03 UTC, AzureAaron approved these changes

2024-02-26 02:31 UTC, kevinthegreat1 requested changes

2024-02-26 02:31 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/Utils.java
>       * Parses /locraw chat message and updates {@link #server}, {@link #gameType}, {@link #locationRaw}, {@link #map}
```suggestion
     * Parses /locraw chat message, updates {@link #server}, {@link #gameType}, {@link #locationRaw}, {@link #map}, and {@link #location},
```

2024-02-26 02:31 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/Utils.java
> +     * It also invokes location change event.
```suggestion
     * and invokes {@link LocationEvents#CHANGE}.
```

2024-02-26 02:31 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/events/LocationEvents.java
Maybe just put this event in `SkyblockEvents` so less class spam.

2024-05-16 17:34 UTC, viciscat commented
Superseded by #716

2024-05-16 17:34 UTC, closed without merging