Make the crafting UI look like the vanilla crafting table
SkyblockerMod/Skyblocker pull request #599
Opened 2024-03-16 17:29 UTC by viciscat

Self explanatory ain't it?

<details>
<summary>High Res Images</summary>

![image](https://github.com/SkyblockerMod/Skyblocker/assets/51047087/d13e2b8d-34cd-48f3-96b4-6b9e53bc998e)

![image](https://github.com/SkyblockerMod/Skyblocker/assets/51047087/6f93093e-a3de-4277-85fc-4e8df4c73940)

</details>

2024-03-16 21:41 UTC, kevinthegreat1 requested changes
Code looks good, some naming convensions, and needs testing.

2024-03-16 21:41 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableHandler.java
> +public class SkyblockCraftingTableHandler extends GenericContainerScreenHandler {
```suggestion
public class SkyblockCraftingTableScreenHandler extends GenericContainerScreenHandler {
```

2024-03-16 21:41 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreen.java
> +    static class Dummy extends AbstractRecipeScreenHandler<SimpleInventory> {
```suggestion
    static class DummyRecipeScreenHandler extends AbstractRecipeScreenHandler<SimpleInventory> {
```

2024-03-17 01:30 UTC, x-yingcan-x commented
pls remove the `quick craft` in texture, we all know what it is and this will only make it worse in I18N support (hard to translate)

2024-03-17 11:47 UTC, viciscat commented
> pls remove the `quick craft` in texture, we all know what it is and this will only make it worse in I18N support (hard to translate)
Not in the texture, however the string is hard coded. Imma change that

2024-03-17 12:03 UTC, Julienraptor01 commented
> pls remove the `quick craft` in texture, we all know what it is and this will only make it worse in I18N support (hard to translate)

I kinda agree with the fact the quick craft line is kinda bad ?
How does Hypixel communicate that these slots are quick-craft ?
If they don't put any mention we probably should neither

2024-03-17 12:12 UTC, viciscat commented
tooltip is already there cuz it literally just displays the items in that slot. So I'm gonna yeet the string

2024-03-17 12:15 UTC, Julienraptor01 commented
> tooltip is already there cuz it literally just displays the items in that slot. So I'm gonna yeet the string

it displays the glass panes ?
and also display the barrier blocks ?
would there be a way to show these as empty, but still show the tooltips
and also obv make sure that putting items in those slots behave as vanilla / is impossible (which is probably easier to do)
did you prevent the players from even switching items from the cursor slot to the output slot ?

2024-03-17 12:16 UTC, viciscat commented
I made barrier not render cuz it looked weird, but glass panes still render. They don't look too out of place

2024-03-17 12:22 UTC, Julienraptor01 commented
> I made barrier not render cuz it looked weird, but glass panes still render. They don't look too out of place
> 
> EDIT: did not prevent clicking on output slot aka barrier, and base skyblocker prevents clicking on black stained glass panes

actually preventing to click could go wrong as if you click with the same item, it does things, so not preventing the output one is fine
can you show an example with quickcraft slots with panes ?

2024-03-17 12:31 UTC, viciscat commented
~~test it yourself~~

Here's when ya got no crafts
<details>
<summary>In spoiler cuz these images real big</summary>

![image](https://github.com/SkyblockerMod/Skyblocker/assets/51047087/8c79b4b9-bdfc-40e6-a5b4-f607fdd7e4c8)

Simple hover for More Crafts
![image](https://github.com/SkyblockerMod/Skyblocker/assets/51047087/06bcb3ed-42ec-428d-bd2c-f4fa598d7460)


</details>

2024-03-17 12:36 UTC, Julienraptor01 commented
> ~~test it yourself~~
> 
> Here's when ya got no crafts
> <details>
> <summary>In spoiler cuz these images real big</summary>
> 
> ![image](https://github.com/SkyblockerMod/Skyblocker/assets/51047087/8c79b4b9-bdfc-40e6-a5b4-f607fdd7e4c8)
> 
> Simple hover for More Crafts
> ![image](https://github.com/SkyblockerMod/Skyblocker/assets/51047087/06bcb3ed-42ec-428d-bd2c-f4fa598d7460)
> 
> 
> </details>

Is the more craft tooltip hardcoded ?
Or do you extract info from the tooltips of the + head item ?

2024-03-17 12:38 UTC, viciscat commented
hard coded, I can try and get the original tooltip

2024-03-17 23:24 UTC, AzureAaron requested changes

2024-03-17 23:24 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreen.java
> +            if(moreCraftsButton != null) moreCraftsButton.setPosition(this.x + 174, this.y+62);
format

2024-03-17 23:24 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreen.java
> +        context.drawGuiTexture(QUICK_CRAFT, i+173, j, 0, 25, 84);
format

2024-03-17 23:24 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreen.java
> +        boolean bl = mouseX < (double)left || mouseY < (double)top || mouseX >= (double)(left + this.backgroundWidth) || mouseY >= (double)(top + this.backgroundHeight);
add spaces between casts

2024-03-17 23:24 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreenHandler.java
> +        for (int i = 0; i < rows*9; i++) {
format

2024-03-17 23:24 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreenHandler.java
> +        for (int i = rows*9; i < slots.size(); i++) {
format

2024-03-17 23:24 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreenHandler.java
> +            int y = (slot/9 -  1) * 18 + 8;
format

2024-03-17 23:24 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreenHandler.java
> +        return new int[]{30 + gridX*18, 17+gridY*18};
format 3x

2024-04-01 00:44 UTC, kevinthegreat1 requested changes
Forgot to add config. Also this doesn't work if `betterPartyFinder` is turned off. See `HandledScreenProviderMixin`.

2024-04-03 20:54 UTC, kevinthegreat1 approved these changes

2024-04-04 02:51 UTC, merged