Fix #606
SkyblockerMod/Skyblocker pull request #610
Opened 2024-03-22 07:46 UTC by viciscat

Fixes #609 
Was caused bye `client.player` being null when not in game

2024-03-22 08:40 UTC, VermeilChan commented
works in game but doest work in menu

2024-03-22 08:41 UTC, VermeilChan commented
![image](https://github.com/SkyblockerMod/Skyblocker/assets/120065660/6a34106f-2e73-46a6-b3a3-b289d8a8710e)

2024-03-22 08:42 UTC, viciscat commented
Need to wait for the Pull Request to get merged

2024-03-24 05:09 UTC, AzureAaron requested changes

2024-03-24 05:09 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
There needs to be a space in front of the `:` in the ternary expressions.

2024-03-24 19:21 UTC, AzureAaron approved these changes

2024-03-24 19:31 UTC, merged