Fancy Auctions Browser: The Sequel
SkyblockerMod/Skyblocker pull request #614
Opened 2024-03-24 17:11 UTC by viciscat

_Uh hello? Welcome to the new and improved "Fancy Auctions Browser" PR. Now, I want you to forget everything you've heard or seen in the previous PR._
This is a rewrite of my old PR to make it actually work and make it less stupid code wise (hopefully).

<details>
  <summary>Excessively large images from the previous PR. Same thing, give or take a few differences.</summary>

![image](https://github.com/SkyblockerMod/Skyblocker/assets/51047087/f58cc4e3-1b84-444b-9cc1-bbdd1bddb3b9)

![image](https://github.com/SkyblockerMod/Skyblocker/assets/51047087/6c6b031b-b38c-4ea2-bb63-05de8ab8e241)

![image](https://github.com/SkyblockerMod/Skyblocker/assets/51047087/80ad6f86-a6be-4241-a0cb-d7d3a5942500)

![image](https://github.com/SkyblockerMod/Skyblocker/assets/51047087/27676435-b6dc-4a6b-93a1-9de3fd793ca5)

</details>

Responding to me in the previous PR: yes you missed edge cases you IDIOT. There might still be some edge cases.

2024-03-30 19:22 UTC, kevinthegreat1 requested changes
Code looks pretty good.

2024-03-30 19:22 UTC, kevinthegreat1 commented on src/main/resources/skyblocker.mixins.json
> +  ]
You probably generated this accessor, which is fine, but just remember to put it in `client` with the other mixins

2024-04-12 20:49 UTC, AzureAaron requested changes

2024-04-12 20:49 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/mixin/accessor/SlotAccessor.java
> +    void setX(int x);
mm you could add a space here

2024-04-12 20:49 UTC, AzureAaron commented on src/main/resources/skyblocker.mixins.json
> +    "accessor.SlotAccessor"
Move this to the rest of them so its alphabetical

2024-04-12 20:49 UTC, AzureAaron commented on src/main/resources/skyblocker.mixins.json
> +  "mixins": []
remove this

2024-04-12 22:11 UTC, kevinthegreat1 approved these changes
Works well. I fixed some small things. Item prices should be represented as longs since they can go over the integer limit. I also used `ItemUtils.getNbtTooltips` instead of `stack.getTooltip(client.player, TooltipContext.BASIC)`, which saves a bit of processing.

There is stil a bug that when a slot changes from and item to empty, it doesn't get updated, resulting in the cheap highlight still showing. If this can't be properly fixed, we can just not render the highlight if the slot is empty.

2024-04-13 22:18 UTC, merged