Warp command auto-complete
SkyblockerMod/Skyblocker pull request #630
Opened 2024-04-03 21:52 UTC by viciscat

I will not take inquiries for my poor coding decisions.

reasons:
1. I'm tired and I want to sleep and I have school tomorrow
2. Reason 2
3. bob

2024-04-03 21:56 UTC, AzureAaron requested changes

2024-04-03 21:56 UTC, AzureAaron commented on src/main/resources/skyblocker.mixins.json
> +    "CommandTreeS2CPacketMixin"
The list is supposed to be alphabetized :<

2024-04-03 21:56 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/mixin/CommandTreeS2CPacketMixin.java
> +        if (WarpAutocomplete.COMMAND_THING != null && original instanceof LiteralCommandNode<?> literalCommandNode && literalCommandNode.getLiteral().equals("warp") && (Utils.isOnHypixel())) {
`Utils.isOnHypixel` doesn't need to be wrapped in brackets

2024-04-03 21:56 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/WarpAutocomplete.java
> +
could remove this whitespace line

2024-04-04 19:55 UTC, kevinthegreat1 approved these changes
Works well

2024-04-09 19:57 UTC, merged