Custom Animated Dyes
SkyblockerMod/Skyblocker pull request #634
Opened 2024-04-05 08:50 UTC by AzureAaron

Ever wanted an animated dye on your armour set but you either couldn't afford one or felt too restricted by having to choose between warden dye and lucky dye? Well then this new feature is for you!

You will be able to apply a custom animated dye to your armour by supplying two HEX colours from which the mod will create a gradient, you will also supply how many "samples" or colours are to be taken from this gradient (the progression is linear if you are into the math), whether you want the colours to cycle back and forth or not, and optionally a delay of how many ticks it'll take for the next colour to be progressed to.

Command Syntax: `/skyblocker custom animatedDye [<hex1>] <hex2> <samples> <cycleBack> [<tickDelay>]`
Ex: `/skyblocker custom animatedDye 0061ff 60efff 10 true 4`

I've also added a tip about this new feature as it's very cool.

2024-04-05 19:11 UTC, kevinthegreat1 reviewed
Looks good but didn't test. Putting in bleeding edge for now.

2024-04-08 19:31 UTC, viciscat requested changes
2 things:
- If I read the code correctly it should show the color that is applied, yet it isn't showing, doesn't seem to work for static dye color either. <details>
![image](https://github.com/SkyblockerMod/Skyblocker/assets/51047087/9b1efb1b-4e54-4f65-97ae-d361c05dce70)
</details>

- an argument type for hex would be appreciated to show if you goofed it or nah. I didn't know if needed to put #FF0000 or 0xFF0000 or just FF0000

Apart it works great, my glacite armor is no glowwwyyyyyy 10/10

2024-04-08 20:46 UTC, AzureAaron commented
> 2 things:
> 
> * If I read the code correctly it should show the color that is applied, yet it isn't showing, doesn't seem to work for static dye color either. 
>   ![image](https://private-user-images.githubusercontent.com/51047087/320626002-9b1efb1b-4e54-4f65-97ae-d361c05dce70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MDk0ODAsIm5iZiI6MTcxMjYwOTE4MCwicGF0aCI6Ii81MTA0NzA4Ny8zMjA2MjYwMDItOWIxZWZiMWItNGU1NC00ZjY1LTk3YWUtZDM2MWMwNWRjZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDIwNDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMjI2Y2ZmNzhmZDEyMzhkMzljY2NiZTY4ODM0NjE4NGRhYmQ5ZjRiYWIzMzk5YjZjN2E3N2VjYWFjOTNkZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8_EElazF50X-xk2yD7ziAGqMwzTgJl2XxlfTeG1_6xQ)
> 
> * an argument type for hex would be appreciated to show if you goofed it or nah. I didn't know if needed to put #FF0000 or 0xFF0000 or just FF0000
> 
> Apart it works great, my glacite armor is no glowwwyyyyyy 10/10

1: Not supported functionality.
2: None of the other hex accepting arguments have anything special.

2024-04-09 15:18 UTC, viciscat commented
> Not supported functionality. 

sad but oh well
>None of the other hex accepting arguments have anything special.

why noooootttt


anyways apart from those nitpicks it works so i'm just gonna approve

2024-04-09 15:18 UTC, viciscat approved these changes

2024-04-09 19:58 UTC, merged