Dungeon Crypts Message
SkyblockerMod/Skyblocker pull request #640
Opened 2024-04-07 13:15 UTC by Fluboxer

Another small change that I'm surprised that even 1.8 mods don't have. It just says in _party_ chat if you lack crypts and it will also say number you lack - all that after reaching threshold 

Default one is 270, which is good for mist S+ runs. For S runs or for some slow/too fast S+ teams you may manually change threshold in config

2024-04-11 11:00 UTC, Fluboxer commented
changed default threshold - 270 conflicts with 270 message due to hypixel blocking two instant messages 

I set it to 250, tho 260 or >270 will also do - but I don't want this message to get lost in flood of "hey we got 270" from whole party

2024-04-16 23:41 UTC, kevinthegreat1 requested changes

2024-04-16 23:41 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
> +		if (!sentCrypts && score >= SCORE_CONFIG.dungeonCryptsMessageThreshold && (5 > getCrypts())) {
```suggestion
		if (!sentCrypts && score >= SCORE_CONFIG.dungeonCryptsMessageThreshold && getCrypts() < 5) {
```

2024-04-16 23:41 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
> +		if (!sentCrypts && score >= SCORE_CONFIG.dungeonCryptsMessageThreshold && (5 > getCrypts())) {
Also please save the result from `getCrypts()` instead of calling it twice.

2024-04-17 00:00 UTC, kevinthegreat1 requested changes
I meant variable, not field.

2024-04-17 00:00 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
> +	private static int crypts;
```suggestion
```

2024-04-17 00:00 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
> +		crypts = getCrypts();
```suggestion
		int crypts = getCrypts();
```

2024-04-18 03:23 UTC, kevinthegreat1 commented
Tested btw.

2024-04-19 14:08 UTC, merged