Prevent teammates glow during Livid
SkyblockerMod/Skyblocker pull request #652
Opened 2024-04-15 04:10 UTC by kevinthegreat1

Prevents anything other than Livid or other explicitly glowing mobs to glow.  
Adds `DungeonBoss` to check for boss. See `DungeonManager.isInBoss()` and `DungeonManager.getBoss()`.  

Hopefully doesn't conflict with Aaron's #647.  

<img width="1440" alt="Screenshot 2024-04-15 at 00 02 35" src="https://github.com/SkyblockerMod/Skyblocker/assets/92656833/9c088972-72a4-48f1-84ab-5a43f465e4b4">

2024-04-18 05:06 UTC, AzureAaron requested changes

2024-04-18 05:06 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonBoss.java
> +    public final String message;
I think these can be made private?

2024-04-18 14:22 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonBoss.java
> +    public final String message;
```suggestion
    private final int floor;
    private final String message;
```

2024-04-18 14:23 UTC, kevinthegreat1 commented
> [!NOTE]  
> Squash when merging

2024-04-19 16:51 UTC, AzureAaron approved these changes

2024-04-19 22:06 UTC, merged