Farming hud improvements
SkyblockerMod/Skyblocker pull request #685
Opened 2024-05-05 04:40 UTC by kevinthegreat1

Add coins per hour.  
Fix the mouse not unlocking when the option is turned off.  
Refactor item price calculations.  

<details><summary>Farming Hud</summary>
<p>

<img width="1440" alt="Screenshot 2024-05-05 at 00 24 19" src="https://github.com/SkyblockerMod/Skyblocker/assets/92656833/370209b8-4c70-4ecd-acf6-e1f60f2ed5ca">

</p>
</details>

2024-05-05 16:31 UTC, AzureAaron submitted a review, later dismissed

2024-05-05 16:38 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
>          ProfileComponent profile = stack.get(DataComponentTypes.PROFILE);
```suggestion
        if (!stack.isOf(Items.PLAYER_HEAD) || !stack.contains(DataComponentTypes.PROFILE)) return "";

```

2024-05-05 16:38 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
> +        return profile.properties().get("textures").stream()
```suggestion
        return stack.get(DataComponentTypes.PROFILE).properties().get("textures").stream()
```

2024-05-11 21:11 UTC, kevinthegreat1 commented
Conflicts with #683. Will wait until after #683 is merged.

2024-05-17 21:17 UTC, kevinthegreat1 commented
Add cultivating counter and use normal counter as fallback.
<img width="966" alt="Screenshot 2024-05-17 at 17 14 40" src="https://github.com/SkyblockerMod/Skyblocker/assets/92656833/afa24af6-e230-48ba-89cf-f92da20d939d">

2024-05-23 02:57 UTC, kevinthegreat1 commented
Fix the merge conflict on #683’s side, so all good to review now.

2024-05-24 21:52 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
> +            Map.entry("COCO_CHOPPER", "INK_SACK.3")
Good catch

2024-05-24 21:53 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHud.java
> +        if (matcher == null) return false;
Done in `118c4b7`.

2024-05-24 21:53 UTC, kevinthegreat1 commented
All fixed up, including the crash.

2024-05-25 17:39 UTC, kevinthegreat1 commented
I tried switching over to `ClientTickEvents.END_CLIENT_TICK` but since it updates slower, block per second shows 21. I tried reproducing what you're experiencing but couldn't.

2024-05-30 06:43 UTC, AzureAaron requested changes
The farming hud icon using the main hand stack is a bit weird.

Although the HUD is broken in the main menus and stuff (when the player has no main hand stack)

2024-05-31 13:20 UTC, kevinthegreat1 commented
Tested btw.

<details><summary>Farming Hud</summary>
<p>
<img width="966" alt="Screenshot 2024-05-31 at 21 17 48" src="https://github.com/SkyblockerMod/Skyblocker/assets/92656833/538c3abd-359b-48bc-b214-ecda92a21365">
</p>
</details>

2024-06-05 11:13 UTC, Fluboxer commented
> Just found out that the cultivating counter disappears after 100m. That got me thinking, would it be possible to calculate crops/min using bps (or blocks per min if necessary) and multiplying that by average drops per crop * (1+(fortune/100)) and then save the amount ever farmed somewhere?

is there a need to? It is still here, just not displayed

2024-06-07 04:37 UTC, kevinthegreat1 commented
All done.

2024-06-10 03:48 UTC, merged