Sign calculator
SkyblockerMod/Skyblocker pull request #686
Opened 2024-05-05 11:15 UTC by olim88

adds ability to do calculations when inputting number into signs and a calculate command

# sign input
![image](https://github.com/SkyblockerMod/Skyblocker/assets/70377847/0fc40d87-8148-41b6-9846-857f586c108b)
![image](https://github.com/SkyblockerMod/Skyblocker/assets/70377847/4eeba99b-de3b-44a0-a9c7-2d18b3367a78)

# command
![image](https://github.com/SkyblockerMod/Skyblocker/assets/70377847/1b260b6a-242d-49ab-8dac-bd34d0b8de96)
![image](https://github.com/SkyblockerMod/Skyblocker/assets/70377847/b2879ac2-058e-4fa8-8ec7-c0aa73e245a9)

I have created custom calculator utility for this using a shunting yard algorithm to convert calculation to RPN and then calculating the answer. it also supports (s, k, m, b) and created tests for this.

also tested in game bazaar and ah

2024-05-05 14:16 UTC, viciscat commented
Another banger by olim. Do you think it would be doable to have an interface that a screen could implement to have it somewhere else? i.e. the popup to set the price/bid in fancy AH.

2024-05-05 15:49 UTC, olim88 commented
>  implement to have it somewhere else

This should not be to hard. If the renderSign method in SignCalculator to a location (add possible renamed) then it should work were ever this is called. is this the sort of thing you meant

2024-05-05 16:13 UTC, Fluboxer commented
add "e" for "enchanted", equals 160 (2.5 stacks)

2024-05-05 16:16 UTC, viciscat commented
> This should not be to hard. If the renderSign method in SignCalculator to a location (add possible renamed) then it should work were ever this is called. is this the sort of thing you meant

yea that's good enough

2024-05-05 16:17 UTC, kevinthegreat1 commented
Maybe only works if you have a `=` sign in front like `=4s * 5`. Also would be nice to have `purse` be the number of coins you have in your purse.

2024-05-05 16:19 UTC, viciscat requested changes

2024-05-05 16:19 UTC, viciscat commented on src/main/java/de/hysky/skyblocker/skyblock/calculators/SignCalculator.java
> +        input = messages[0];
Passing a string array only to use the first one is kinda pointless in my opinion. Just pass a normal string

2024-05-06 17:31 UTC, olim88 commented
> add "e" for "enchanted"
> have purse be the number of coins you have in your purse

good idea. i have added this and put a key in the tooltip so players know its there
> Maybe only works if you have a = sign in front

i feel like this is a nice idea and some will like it however i like to be reassured what the value of the sign is going to be even if i am just doing something like 1.02k so i have made it a toggle in the settings so both options are available

2024-05-07 21:49 UTC, viciscat commented
last nitpick and I think this PR will be good, add "p" for "purse" maybe? to make it easier and faster to type

2024-05-07 23:31 UTC, Fluboxer commented
> last nitpick and I think this PR will be good, add "p" for "purse" maybe? to make it easier and faster to type

I still don't get how this one would be useful tho

2024-05-08 10:18 UTC, viciscat commented
> I still don't get how this one would be useful tho

make it faster to type or something, faster to type "p" than "purse"

2024-05-10 19:30 UTC, AzureAaron submitted a review, later dismissed

2024-05-10 19:30 UTC, AzureAaron commented on src/main/resources/assets/skyblocker/lang/en_us.json
> +  "skyblocker.config.uiAndVisuals.inputCalculator": "Input Calculator",
Ensure this is in alphabetical order with the rest of the translation strings

2024-05-12 02:29 UTC, kevinthegreat1 approved these changes
There's a tiny bug when you have `requiresEquals` set to true and type a valid equation without the equals sign. When you add the equals sign, it will show as invalid since the equation is not reevaluated when an equals sign is added, but I don't see a good way of fixing this.

2024-05-14 21:04 UTC, merged