Fix quite important AH bug
SkyblockerMod/Skyblocker pull request #689
Opened 2024-05-05 17:25 UTC by viciscat

- fix #687 
- make fluboxer happy

2024-05-05 17:27 UTC, AzureAaron requested changes

2024-05-05 17:27 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionViewScreen.java
> +        if (keyCode == 256) {
Use GLFW constant for clarity as to what key code this is

2024-05-05 17:27 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionViewScreen.java
> +        if (stack.isOf(Items.BLACK_STAINED_GLASS_PANE) || slotId == 13 || slotId >= handler.getRows()*9) return;
spacing in between the math

2024-05-09 21:30 UTC, kevinthegreat1 requested changes

2024-05-09 21:30 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionViewScreen.java
> +        ButtonWidget build = new ButtonWidget.Builder(Text.literal("<"), button -> this.clickSlot(BACK_BUTTON_SLOT))
```suggestion
        ButtonWidget backButton = new ButtonWidget.Builder(Text.literal("<"), button -> this.clickSlot(BACK_BUTTON_SLOT))
```

2024-05-09 21:30 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionViewScreen.java
> +        addDrawableChild(build);
```suggestion
        backButton.setTooltipDelay(Duration.ofSeconds(1));
        addDrawableChild(backButton);
```

2024-05-09 22:02 UTC, kevinthegreat1 approved these changes
The slot change fix is basically a bodge but good enough. Also, I don't think we would have problems with spamming escape since it should close the screen, right?

2024-05-14 01:30 UTC, kevinthegreat1 commented
Squashing because commit history is trivial.

2024-05-14 01:31 UTC, merged