EssenceShopPrice feature
SkyblockerMod/Skyblocker pull request #737
Opened 2024-05-28 21:35 UTC by UpFault

added option to view how much essence will cost from bazaar in lore of Essence Shop Items

2024-05-28 22:09 UTC, kevinthegreat1 commented
Thanks for your great pr’s. As you may see, we currently have quite a few pr’s awaiting review so this might take a while.

2024-05-28 23:17 UTC, UpFault commented
> Thanks for your great pr’s. As you may see, we currently have quite a few pr’s awaiting review so this might take a while.

no worries

2024-05-29 05:39 UTC, UpFault commented
![ZkWnrwz](https://github.com/SkyblockerMod/Skyblocker/assets/76474308/804ebf6a-0210-460f-878c-fef635195200)
![fC9jrWU](https://github.com/SkyblockerMod/Skyblocker/assets/76474308/d33fe8f6-21bc-430f-bb6a-6382d1762723)
![UjRQHSC](https://github.com/SkyblockerMod/Skyblocker/assets/76474308/a18cc143-cce4-4730-bf1e-4463e491e148)


Figured I'd drop these here

2024-05-29 06:52 UTC, UpFault commented
Also I should probably move the config value over to Item Tooltip in the general category rather than UI & Visuals(don't know what I was thinking here.)

2024-05-30 08:31 UTC, Fluboxer commented
May as well take it to your own visitor pr so they have a child - if you lack essence to buy thing, right clicking would just open bz with needed essence in your clipboard

2024-06-02 01:54 UTC, kevinthegreat1 commented
Hi, these pr's still need rebasing since they contain unrelated commits. Here's how you can rebase the pr's. I'm using #737 as an example. First, find the first commit in your pr and selected it, as shown in the first image. Right click and select `Interactively Rebase from Here`. Then select all commits except the ones that you want to keep and select `Drop`, and you should end up like the second image. Finally click `Start Rebasing`.
<img width="1440" alt="Step 1" src="https://github.com/SkyblockerMod/Skyblocker/assets/92656833/fbef7b72-9f57-47c3-aeb3-bd69bb0449d5">
<img width="1440" alt="Step 2" src="https://github.com/SkyblockerMod/Skyblocker/assets/92656833/c64caa6a-5f2e-4dff-831b-cee6cac3dafa">

2024-07-18 06:17 UTC, kevinthegreat1 requested changes

2024-07-18 06:17 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/EssenceShopPrice.java
> +import java.text.DecimalFormatSymbols;
```suggestion
import java.text.NumberFormat;
```

2024-07-18 06:17 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/EssenceShopPrice.java
> +	private static final DecimalFormat DECIMAL_FORMAT = new DecimalFormat("#,###.#", DecimalFormatSymbols.getInstance(Locale.ENGLISH));
```suggestion
	private static final NumberFormat DECIMAL_FORMAT = NumberFormat.getInstance(Locale.US);
```

2024-07-18 06:17 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/EssenceShopPrice.java
> +		LOGGER.info("[Skyblocker] Refreshed essence prices.");
```suggestion
```

2024-07-18 06:17 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
> +                                .build())
This config is a bit messed up. This should be in the `itemTooltip` group.

2024-07-18 06:17 UTC, kevinthegreat1 commented on src/main/resources/assets/skyblocker/lang/en_us.json
> +  "skyblocker.config.general.itemTooltip.showEssenceCost": "Show Essence Cost",
Right now for all the price tooltips, it says "enable ...", but "show ..." is arguably better. So keep it as is?

2024-07-18 07:03 UTC, kevinthegreat1 approved these changes

2024-07-18 08:05 UTC, kevinthegreat1 approved these changes

2024-07-18 08:07 UTC, merged