Networth
SkyblockerMod/Skyblocker pull request #806
Opened 2024-06-27 16:47 UTC by viciscat

I totally made all the commits in this PR. Don't check the commit authors, i'm a trustworthy guy mhm.

2024-06-30 07:13 UTC, kevinthegreat1 commented
Minor conflicts with #781.

2024-07-08 17:46 UTC, viciscat reviewed
cool, just need to fix conflicts :p

2024-07-26 06:25 UTC, kevinthegreat1 commented
This is ready to be rebased. Just fyi you need to extend `SimpleTooltipAdder` instead of `TooltipAdder` now.

2024-08-10 07:09 UTC, kevinthegreat1 requested changes
Just one thing blocking, the `dumpHeldItemNetworthCalculationsCommand`.

2024-08-10 07:09 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/networth/SkyblockItemMetadataRetriever.java
> +		return new IntArrayList();
```suggestion
		return IntList.of();
```

2024-08-10 07:17 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/utils/networth/NetworthDataSuppliers.java
> +public class NetworthDataSuppliers {
so a singleton?

2024-08-10 07:19 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/networth/NetworthDataSuppliers.java
> +public class NetworthDataSuppliers {
Nvm I read this class wrong. I thought it stores data for one particular item stack at a time.

2024-08-11 20:33 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
> +    public static LiteralArgumentBuilder<FabricClientCommandSource> dumpHeldItemNetworthCalculationsCommand() {
yeah I forgot, got removed accidentally during conflict fixes

2024-08-11 22:49 UTC, aiden-powers approved these changes

2024-08-12 04:52 UTC, kevinthegreat1 approved these changes

2024-08-12 07:08 UTC, merged