Add raytracing to the egg finder to make it fairer
SkyblockerMod/Skyblocker pull request #845
Opened 2024-07-15 09:20 UTC by Emirlol

I'm honestly not sure how to explain the changes. Might be better to read commits.
Fixes #832 by adding ray tracing every tick. Also has better logic for waypoints and chat messages, now it doesn't highlight eggs/send messages when the egg was already found in another island, and this state is reset when the egg's reset hour happens, which is at 7, 14, 21 (7am, 2pm, 9 pm)

Also cleans up and improves `SkyblockTime`. Now it includes hour and refreshes every 50 secs (a skyblock hour). There are also events for when the time unit changes value.

2024-07-15 09:32 UTC, Vricken commented
Could the raycast be an option? Like a setting called “enable egg waypoints without seeing them (possibly bannable use at your own risk)” or something like that

2024-07-15 09:33 UTC, Julienraptor01 commented
> Could the raycast be an option? Like a setting called “enable egg waypoints without seeing them (possibly bannable use at your own risk)” or something like that

no, it's not ESP is a cheat and it's an accident that we included such behavior
tho it's fully open source, so feel free to unpatch it, but it won't be released as an option
(this is just my opinion but i think no one on the team want the mod to become a cheat)

2024-07-15 09:43 UTC, Emirlol commented
> > Could the raycast be an option? Like a setting called “enable egg waypoints without seeing them (possibly bannable use at your own risk)” or something like that
> 
> no, it's not, ESP is a cheat and it's an accident that we included such behavior tho it's fully open source, so feel free to unpatch it, but it won't be released as an option (this is just my opinion but i think no one on the team want the mod to become a cheat)

Exactly this. I just never had the thought of whether it was cheaty or not when making it. Took a while to fix due to some skill issues and laziness. This PR is how it should've been since the start.

I know it's currently a bit hard to use, as all it does is tell you if you unobstructed vision to eggs. I was also planning on adding labels for possible locations and egg locator helper for that, but I have other stuff to do for now so those will come separately later on.

2024-07-26 01:49 UTC, AzureAaron requested changes

2024-07-26 01:49 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/EggFinder.java
> +			for (EggType type : EggType.entries) {
there should be some more checks to ensure that this isn't constantly creating an iterator, such as being in skyblock, correct location & time

2024-07-30 10:32 UTC, kevinthegreat1 requested changes

2024-07-30 10:32 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/SkyblockTime.java
> +	});
These should go at the top. Maybe in a block after the logger?

2024-08-02 12:35 UTC, kevinthegreat1 approved these changes

2024-08-03 01:09 UTC, AzureAaron approved these changes

2024-08-03 01:11 UTC, merged