Move to Mod API for isOnSkyblock detection
SkyblockerMod/Skyblocker pull request #854
Opened 2024-07-19 08:52 UTC by AzureAaron

Moves to using the Mod API for `isOnSkyblock` detection. Also fixes the bug where the Skyblock `JOIN` and `LEAVE` events could fire multiple times despite not actually leaving skyblock or joining it from another lobby/game.

Also removes the `isInjected` boolean because it was unused.

2024-07-20 20:47 UTC, viciscat requested changes

2024-07-20 20:47 UTC, viciscat commented on src/main/java/de/hysky/skyblocker/utils/Utils.java
> +                    SkyblockEvents.LEAVE.invoker().onSkyblockLeave();
am i dumb or will this fire every time you go from a non skyblock server to another non skyblock server? wouldn't it need a
```java
if (previousServerType.equals("SKYBLOCK"))
```
or something similar?

2024-07-20 20:51 UTC, viciscat commented on src/main/java/de/hysky/skyblocker/utils/Utils.java
> +                    SkyblockEvents.LEAVE.invoker().onSkyblockLeave();
no? the `else` is for the first `if`

2024-07-26 04:47 UTC, AzureAaron commented
Removed the Debug calls because I run production only with debug enabled and I don't want fancy bars and shit in SMPs.

2024-07-27 20:51 UTC, viciscat approved these changes

2024-07-28 20:30 UTC, merged