[WORKING DRAFT] Better dungeon door detection/overlay
SkyblockerMod/Skyblocker pull request #879
Opened 2024-07-30 17:28 UTC by GatienDoesStuff

I've just spent the day rewriting the code that detects dungeons doors.

Let me know if I'm doing anything wrong / there are any concerns regarding the proposed code.

# Summary of changes compared to current implementation
- Cleanup of now unused functions
- Doors towards the blood room are now detected by looking at the map, allowing them to be rendered no matter where the player currently is in the dungeon (just like `BetterMap` does on 1.8)
- This also means that the fairy room is now highlighted, which wasn't the case before
- Fixes bugs related to the key being picked up naturally after it times out (the door wouldn't get recolored to green)

# Concerns
- Code quality ?
- Hardcoded values for map colors, as well as position code that might not be easily understood
- Currently, the doors are checked for every tick, which might not be a good thing for performance. It could be possible to only check when necessary :
  - Upon starting a run
  - Upon opening a door
  - Upon fairy room being discovered (harder to detect)
  
  Feel free to test those changes, things have been working pretty smoothly on my end, and I haven't been able to find any bugs / wrong placements for the doors.

2024-07-31 06:58 UTC, GatienDoesStuff commented
Just did a dozen runs with this, and I haven't really found any issues, doors are rendering where they're expected to

2024-08-06 16:00 UTC, kevinthegreat1 requested changes
Looks good, just some small things and formatting.

2024-08-06 18:01 UTC, GatienDoesStuff commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/Room.java
> +        else if (matchingRoomsSize == 1) {
My bad on those, I didn't correctly apply the formatting config listed on the wiki.

While the other changes all apply just like you did, it seems like the formatter really doesn't want to have the `else if` on the same line as the closing bracket.
Is it a config I'm missing ? If I apply this, the next person to work on that file might just revert it.

2024-08-06 18:02 UTC, GatienDoesStuff commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
> +        for (int x = nWMostRoom.x + mapRoomSize / 2; x < 127; x += mapRoomSize + 4) {
You're right, this went over my head.

2024-08-06 18:43 UTC, GatienDoesStuff commented
I believe this should be it, minus the small nitpick about `else if` above.

2024-08-08 06:10 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/Room.java
> +        else if (matchingRoomsSize == 1) {
I’m not sure. The intellij default keeps them on the same line.

2024-08-08 06:12 UTC, kevinthegreat1 approved these changes

2024-08-09 06:35 UTC, merged