Add Garden Plots Widget
SkyblockerMod/Skyblocker pull request #929
Opened 2024-08-15 12:55 UTC by viciscat

Adds a nice little widget that shows your plots and highlights the ones with a pest problem.

https://github.com/user-attachments/assets/c95a3633-6a27-4424-a1d9-96219490b305

2024-08-23 17:03 UTC, kevinthegreat1 requested changes
Some suggestions and I think you're good.

2024-08-23 17:03 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/garden/GardenPlotsWidget.java
> +	private record GardenPlot(Item item, String name) {
```suggestion
	// The name is just the plot number.
	private record GardenPlot(Item item, String name) {
```

2024-08-23 17:24 UTC, viciscat commented on src/main/java/de/hysky/skyblocker/skyblock/garden/GardenPlotsWidget.java
> +			String string = displayName.getString();
playerStringList trims the text. I use the space that hypixel adds in front for extra assurance that it's the correct line. But honestly i don't know where else "Plots: " would show up in TAB so why not

2024-08-23 17:26 UTC, viciscat commented on src/main/java/de/hysky/skyblocker/skyblock/garden/GardenPlotsWidget.java
> +		context.drawTexture(BACKGROUND_TEXTURE, 0, 0, 0, 0, getWidth(), getHeight(), getWidth(), getHeight());
real. funnily enough, this texture exists and yet it's not nine slice https://mcasset.cloud/1.21/assets/minecraft/textures/gui/demo_background.png

2024-08-23 17:27 UTC, viciscat commented on src/main/java/de/hysky/skyblocker/skyblock/garden/GardenPlotsWidget.java
> +	private record GardenPlot(Item item, String name) {
it's not, you can rename your plots

2024-08-24 08:51 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/skyblock/garden/GardenPlotsWidget.java
> +	private record GardenPlot(Item item, String name) {
Nevermind then.

2024-09-06 19:21 UTC, kevinthegreat1 submitted a review, later dismissed

2024-11-27 23:00 UTC, kevinthegreat1 commented
This needs to be updated. To make it easier, you should use merge instead of rebase. (This also means that we'll squash the pr.)

2024-11-28 19:51 UTC, kevinthegreat1 submitted a review, later dismissed

2024-12-06 07:07 UTC, AzureAaron approved these changes
looks good

2024-12-06 19:12 UTC, AzureAaron requested changes
Nvm this has a crash:
```
[14:11:16] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:687) ~[?:?]
	at knot/de.hysky.skyblocker.skyblock.garden.GardenPlotsWidget.updateInfestedFromTab(GardenPlotsWidget.java:263) ~[skyblocker-1.22.2-alpha-pr-929-3845601+1.21.3.jar:?]
	at knot/de.hysky.skyblocker.skyblock.garden.GardenPlotsWidget.<init>(GardenPlotsWidget.java:186) ~[skyblocker-1.22.2-alpha-pr-929-3845601+1.21.3.jar:?]
	at knot/net.minecraft.class_490.handler$cce000$skyblocker$addGardenPlotsWidget(class_490.java:1076) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_490.method_25426(class_490.java:51) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25423(class_437.java:308) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1507(class_310.java:1203) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1508(class_310.java:2005) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1574(class_310.java:1870) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1313) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:933) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
```

2024-12-11 13:27 UTC, viciscat commented
> Nvm this has a crash:

Should be impossible but sure lol, `playerList` and `playerStringList` in `PlayerListMgr` should be "synced" but yea idk 🤷

2024-12-22 18:38 UTC, kevinthegreat1 approved these changes

2024-12-23 01:09 UTC, merged

2024-12-23 13:52 UTC, x-yingcan-x commented
![missingno](https://github.com/user-attachments/assets/fa678210-29ea-469e-8b6d-d74ffd9cb695)
do you forget to add texture?

2024-12-23 13:54 UTC, viciscat commented
lmao yes