Added Purse API and Purse Change Event
SkyblockerMod/Skyblocker pull request #950
Opened 2024-08-21 11:43 UTC by Westsi

I added a way to create callbacks for when the player's purse changes and fixed the Utils.getPurse function so that it would not break in the case below. This so that the Purse API can be used to track scavenger coins, useful in profit calculators for slayers and ghosts for instance.

The case that broke the getPurse function:
`Purse: 372,647` works fine, as the prior regex changed that to `372647`.
However, when the purse is being updated with mob kill coins, the line becomes `Purse: 372,768 (+121)`, where the prior regex just removed all non digits, making it  `372768121`. 
To fix this, I added a regex before the existing regex that matches the `(+nnn)` section and removes it.

2024-08-21 12:19 UTC, viciscat commented
This seems a bit of a little random addition (apart from the regex fix)?

2024-08-21 12:32 UTC, Westsi commented
Yeah, I was working on a slayer profit calculator and saw that there was no way of tracking purse changes like this. I thought that it was best to make it a more abstract thing so that it could be used in other similar calculators (ghost profit, bountiful reforge in farming etc). I maybe should have explained that more.

2024-09-06 19:36 UTC, Westsi commented
Merge conflict looks fairly simple to fix to me.

2024-09-08 19:03 UTC, kevinthegreat1 requested changes

2024-09-08 19:03 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/purse/PurseAPI.java
This isn't needed imo. You can just put the login in `Utils`.

2024-09-08 19:03 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/purse/PurseChangeCause.java
> +            // implement slayer quest loss
```suggestion
            // TODO: implement slayer quest loss
```

2024-09-13 18:05 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/purse/PurseAPI.java
I think you should put it in utils. Since you need to rebase this on top of main anyways to solve the merge conflict in `Utils`.

2024-09-14 15:50 UTC, Westsi commented
Done @kevinthegreat1

2024-09-22 00:20 UTC, kevinthegreat1 commented
This pr needed to be rebased. I have done that for you. I apologize for the very rapidly changing main branch, but that's bound to happen to an interdependent project like this, so it would be nice if you could deal with these situations.

2024-09-22 01:27 UTC, kevinthegreat1 commented
This api was a bit messy. I have rewritten it. Feel free to take a look but it should be good now.

2024-09-22 01:28 UTC, kevinthegreat1 submitted a review, later dismissed

2024-09-22 01:33 UTC, kevinthegreat1 commented on src/main/java/de/hysky/skyblocker/utils/purse/PurseChangeCause.java
> +    MOB_KILL(),
```suggestion
    MOB_KILL,
```

2024-09-22 01:34 UTC, kevinthegreat1 submitted a review, later dismissed

2024-11-22 21:49 UTC, kevinthegreat1 approved these changes

2024-11-22 21:51 UTC, kevinthegreat1 commented
> [!Note]
> Squash

2024-11-23 00:59 UTC, merged