Title hud refactor
SkyblockerMod/Skyblocker pull request #951
Opened 2024-08-21 17:18 UTC by kevinthegreat1

Fix some bugs with dragging, hitbox, scaling, etc.
Cleaned up code.

Depends on #816.

https://github.com/user-attachments/assets/f476984f-0879-4eff-a52f-2f9617d4adb1

2024-09-15 17:34 UTC, kevinthegreat1 commented
> [!note]
> Squash please.

2024-12-20 03:28 UTC, kevinthegreat1 commented
Ready for review.

2024-12-23 09:54 UTC, AzureAaron requested changes

2024-12-23 09:54 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/EmptyWidget.java
You probably meant to put this in the same package as the `AbstractWidget`.

2024-12-23 09:54 UTC, AzureAaron commented on src/main/java/de/hysky/skyblocker/utils/render/title/TitleContainerConfigScreen.java
> +	private <T extends Enum<T>> T cycleBackwards(T current) {
Can't these enum methods be static? Maybe they could go somewhere too

2024-12-30 01:18 UTC, merged